export const GET_COCKTAILS = "GET_COCKTAILS";
export const UPDATE_COCKTAILS= "UPDATE_COCKTAILS";
export const UPDATE_USER_INGREDIENTS = "UPDATE_USER_INGREDIENTS";
export const DELETE_USER_INGREDIENT = "DELETE_USER_INGREDIENT";
export const SHOW_ALL_COCKTAILS = "SHOW_ALL_COCKTAILS";